//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_PROJECT_FILIPPOV_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavchik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postavchik()
        {
            this.Tovar = new HashSet<Tovar>();
        }
    
        public int IDPostavchik { get; set; }
        public string NamePostavchik { get; set; }
        public string Adres { get; set; }
        public Nullable<int> Tel { get; set; }
        public Nullable<int> Rekveziti { get; set; }
        public string NameTovar { get; set; }
        public Nullable<int> Articul { get; set; }
        public string VidTovara { get; set; }
        public Nullable<int> StoimostEdTovara { get; set; }
        public int IDTovar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tovar> Tovar { get; set; }
    }
}
